language: rust
rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: stable
  fast_finish: true

cache: cargo
script:
  - RUST_BACKTRACE=1 cargo build --verbose --all
  - RUST_BACKTRACE=1 cargo test --verbose --all --features async-std-runtime
  - RUST_BACKTRACE=1 cargo test --verbose --all --features tokio-runtime
  # - cargo bench