[package]
name = "mobc"
version = "0.4.1"
authors = ["importcjj <importcjj@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT/Apache-2.0"
description = "A generic connection pool with async/await support"
repository = "https://github.com/importcjj/mobc"
categories = ["asynchronous", "network-programming"]
keywords = ["database", "pool", "async", "await"]
documentation = "https://docs.rs/mobc/latest/mobc/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["tokio"]
unstable = []

[dependencies]
futures = "0.3"
tokio = { version = "0.2.6", features=["rt-core", "time"], optional = true }
async-std = { version = "1.0", features=["unstable"], optional = true }
log = "0.4"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
tokio-postgres = "=0.5.0-alpha.2"
env_logger = "0.7"

[package.metadata.docs.rs]
features = ["tokio", "unstable"]