[package]
name = "mobc"
version = "0.4.0-alpha.0"
authors = ["importcjj <importcjj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features=["rt-core", "time"] }
log = "0.4"

[dev-dependencies]
tokio = { version = "0.2", features = ["macros",  "rt-threaded"] }
tokio-postgres = "=0.5.0-alpha.2"
env_logger = "0.7"
deadpool-postgres = "0.4"