[package]
name = "mobc-postgres"
version = "0.1.0"
authors = ["importcjj <importcjj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mobc = { path = ".." }
tokio-postgres = "0.4.0-rc.3"
futures_01 = { version = "0.1", package = "futures"}

[dev-dependencies]
tokio = "0.2.0-alpha.6"